# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

datafile <- system.file(c("pop2025.RDS"), package = "pevrdc")

pops <- readRDS(datafile)
population <- agg_pop(naissance_mois_admin, orgunitlevel2, month = 1, pops = pops)

# Apply test on my function
test_that("agg_pop outputs a dataframe of 2 columns, one character and the other numeric", {
  expect_true(ncol(population) == 2)
  expect_false(is.numeric(population[,1]))
  expect_false(is.character(population[,2]))
})

datafile <- system.file(c("pop2025.RDS"), package = "pevrdc")

pop <- readRDS(datafile)

pop <- clean_dhis_names(pop, column = orgunitlevel3, has_prefix = 2, suffix = "Zone de Sante")




test_that("clean_dhis_names removes all the suffixes", {
  expect_true(sum(grepl("(Zone de Sante)$", pop$orgunitlevel1)) == 0)
})
