# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

datafile <- system.file(c("vacc_data.RDS"), package = "pevrdc")

vacc <- readRDS(datafile)
penta1 <- vaccine_sums(vacc, DTC1, District, 2)
penta3 <- vaccine_sums(vacc, DTC3, District, 2)

# Apply test on my function
test_that("vaccine_sums coherently aggregates vaccines numbers", {
  expect_true(sum(penta3$DTC3) <= sum(penta1$DTC1))
})
