# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.


datafile <- system.file(c("vacc_data.RDS", "pop2025.RDS"), package = "pevrdc")

vacc <- readRDS(datafile[1])
pops <- readRDS(datafile[2])
penta1 <- vaccine_sums(vacc, DTC1, District, 2)
penta1_cov <- vaccine_coverage(penta1, DTC1, District, month = 2, pops = pops)
penta3 <- vaccine_sums(vacc, DTC3, District, 2)
penta3_cov <- vaccine_coverage(penta3, DTC3, District, month = 2, pops = pops)
variables1 <- c("orgunitlevel3", "DTC1", "survivants_mois_admin", "survivant_mois_ajust", 
"DTC1_admin", "DTC1_ajust", "zero_dose_admin", "zero_dose_ajust"
)
variables2 <- c("orgunitlevel3", "DTC3", "survivants_mois_admin", "survivant_mois_ajust", 
"DTC3_admin", "DTC3_ajust"
)






test_that("vaccine_coverage outputs expected variables and variables types", {
  expect_true(all(colnames(penta1_cov) == variables1))
  expect_true(all(colnames(penta3_cov) == variables2))
  types <- table(unlist(Map(function(x)typeof(penta1_cov[[x]]), variables1)))
  expect_true(types["double"] == 7)
  types2 <- table(unlist(Map(function(x)typeof(penta3_cov[[x]]), variables2)))
  expect_true(types2["double"] == 5)

 # expect_error(my_median("text"))
})


