# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.


x <- c(FALSE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE)

test_that("is_outbreak  works properly and show error if needed", {
  expect_equal(sum(is_outbreak(x)), 7)
})

