# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

df <- data.frame(A = c("aè", "bè", "cè"), B = c("èt", "èx", "èy"))

df_correct <- correct_accent(df, "è", "e")

test_that("correct_accent replaces all the accented characters in the dataset", {
  expect_true(sum(grepl("e$", df_correct$a)) == sum(grepl("è$", df$A)) )
  expect_true(sum(grepl("^e", df_correct$b)) == sum(grepl("^è", df$B)) )
})


