# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function that adds DRC antennes to a dataset not having them
#'
#' @param data A dataset with no variable containing antennes, usually DHIS 2 datasets  
#' @param province A Column with province
#' @param zone A column with health zones
#' @param rename_antenne A logical to indicate renaming antennes following DHIS 2 standard 
#'
#' @return
#' A dataframe with a variable with antennes
#' @export
#'



add_antennes <- function(data, province, zone, rename_antenne = TRUE) {
  
  stopifnot(!is.null(data), is.data.frame(data))
  

 
  level <- c(deparse1(substitute(province)), deparse1(substitute(zone)))
  
  antennes <- get("antennes", "package:pevrdc")
  colnames(antennes) <- c(level[1], "antenne", level[2])
  data$zs <- trimws(gsub("^[A-Za-z]{2}|Zone de Sant[e\u00e9]$", "", data[[level[2]]]), "both")
  data$prov<- trimws(gsub("^[A-Za-z]{2}|Province$", "", data[[level[1]]]), "both")
    
    merged_data <- merge(data, antennes, by.x = c("prov","zs"), by.y = level)
    
    merged_data$zs <- NULL
    merged_data$prov <- NULL
    

  
  if (rename_antenne) {
    merged_data$orgunitlevel6 <- merged_data$antenne
    
    merged_data$antenne <- NULL
    
    cat("Antenne column is renamed orgunitlevel6")
  }
  
  
  return(merged_data)
}





