# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function that adds DRC antennes to a dataset not having them
#'
#' @param data A dataset with no variable containing antennes, usually DHIS 2 datasets  
#' @param dhis A boolean to indicate whether the dataset is from the DHIS 2, set to TRUE as default
#' @param zone_sante A variable with health zones names if data are not from DHIS 2, set to NULL as default
#' @param rename_antenne A logical to indicate renaming antennes following DHIS 2 standard 
#'
#' @return
#' A dataframe with a variable with antennes
#' @export
#'

add_antennes <- function(data, dhis = TRUE, zone_sante = NULL, rename_antenne = TRUE) {
  stopifnot(!is.null(data), is.data.frame(data))
  
  if (!dhis) {
    if (!dhis & missing(zone_sante)) {
      stop("zone_sante variable not supplied as data are not from the DHIS 2")
    }
  }
  
  antennes <- get("antennes", "package:hpdDRC")
  
  if (!dhis && !missing(zone_sante)) zone_sante <- deparse1(substitute(zone_sante))
  
  if (!dhis) {
    merged_data <- tryCatch({merge(data, antennes, by.x = zone_sante, by.y = "zonesante", rename_antenne = TRUE)}, 
                            error = function(e) message("There is an error: ",e))
    
    return(merged_data)
  }
  
  data$zs <- trimws(gsub("^[A-Za-z]{2}|Zone de Sant[e\u00e9]$", "", data[["orgunitlevel3"]]), "both")
  
  merged_data <- merge(data, antennes, by.x = "zs", by.y = "zonesante")
  
  merged_data$zs <- NULL
  
  if (rename_antenne) {
    merged_data$orgunitlevel6 <- merged_data$Antenne
    
    merged_data$Antenne <- NULL
    
    cat("Antenne column is renamed orgunitlevel6")
  }
  
  
  return(merged_data)
}


