# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function that aggregates the immunization population tallies of DRC per organization level using built-in 2025 population dataset
#'
#' @param var Column name of the variable containing the population numbers. For the pops dataset monthly targets immunization use naissance_mois_ajust or survivant_mois_ajust. For surveillance use population_totale  
#' @param group The organization level orgunitlevel1 for country, orgunitlevel2 for province, orgunitlevel3 for district and orgunitlevel6 for antennes
#' @param month A numeric value between 1 and 12 to specify the number of months for immunization targets
#' @param pops A dataframe with population data 
#'
#' @return
#' A dataframe of aggregated populations 
#' @export
#'
#' @examples
#'
#' datafile <- system.file(c("pop2025.RDS"), package = "pevrdc")
#'
#' pops <- readRDS(datafile)
#' agg_pop(naissance_mois_admin, orgunitlevel2, month = 8, pops = pops)
#'
#' agg_pop_2("naissance_mois_admin", "orgunitlevel2", month = 8, pops = pops)
agg_pop <- function(var, group, month = 1, pops) {

  agg_pop_q(substitute(var), substitute(group), month, pops = pops)
}


#' A version of agg_pop that does not use NSE, more convenient to use within other functions. Variables arguments are characters
#'
#' @param var Column name of the variable containing the population numbers. For the pops dataset monthly targets immunization use naissance_mois_ajust or survivant_mois_ajust. For surveillance use population_totale  
#' @param group The organization level orgunitlevel1 for country, orgunitlevel2 for province, orgunitlevel3 for district and orgunitlevel6 for antennes
#' @param month A numeric value between 1 and 12 to specify the number of months for immunization targets
#' @param pops A dataframe with population data
#' @importFrom stats aggregate reformulate
#' @return
#' A dataframe of aggregated populations 
#' @export
#'

agg_pop_2 <- function(var, group, month = 1, pops) {
  # --- Argument checks ---
  stopifnot(is.character(var), length(var) == 1)
  stopifnot(is.character(group), length(group) >= 1)
  stopifnot(is.numeric(month), month >= 1, month <= 12)
  stopifnot(var %in% names(pops))
  stopifnot(all(group %in% names(pops)))

  # --- Aggregate ---
  agg_data <- stats::aggregate(
    stats::reformulate(group, response = var),
    data = pops,
    FUN = sum
  )

  # --- Apply month multiplier when appropriate ---
  if (!grepl("totale", var))
    agg_data[[var]] <- agg_data[[var]] * month

  return(agg_data)
}


#' Core of agg_pop not exported. A function that aggregates the immunization population tallies of DRC per organization level using built-in 2025 population dataset
#' @param var Column name of the variable containing the population numbers. For the pops dataset monthly targets immunization use naissance_mois_ajust or survivant_mois_ajust. For surveillance use population_totale  
#' @param group The organization level orgunitlevel1 for country, orgunitlevel2 for province, orgunitlevel3 for district and orgunitlevel6 for antennes
#' @param month A numeric value between 1 and 12 to specify the number of months for immunization targets
#' @param pops  A dataframe with population data
#' @importFrom stats aggregate reformulate setNames
#' @return
#' A dataframe of aggregated populations 
agg_pop_q <- function(var, group, month = 1, pops) {

  var1 <- {if(is.character(var)) as.character(var) else eval(var, stats::setNames(as.list(names(pops)), names(pops)), parent.frame())}
  group1 <- eval(group, stats::setNames(as.list(names(pops)), names(pops)), parent.frame())
  
   if(month < 1 || month > 12)
    stop("month should be between 1 and 12")
  
  
  stopifnot(is.numeric(pops[[var1]]))

  agg_data <- stats::aggregate(
    stats::reformulate(group1, response = var1),
    data = pops,
    FUN = sum
  )

  if(!grepl("totale",var1))
    agg_data[[var1]] <-agg_data[[var1]] * month

  return(agg_data)
}

#' A function that removes DRC DHIS prefixes and suffixes 
#'
#' @param data The dataset containing variables to be cleaned  
#' @param column The column containing values to be cleaned espcially organization levels of DRC EPI
#' @param has_prefix An integer specifying the number of characters of the prefix to be removed. Set to 0 if no prefix
#' @param suffix A character value that specifies the suffix to be removed
#'
#' @return
#' A dataframe with cleaned names
#' @export
#'
#' @examples
#'
#' datafile <- system.file(c("pop2025.RDS"), package = "pevrdc")
#'
#' vacc <- readRDS(datafile)
#' clean_dhis_names(vacc, column = orgunitlevel2, has_prefix = 2, suffix = "Province")
#'
#' clean_names_dhis(vacc$orgunitlevel2,  has_prefix = 2,
#'                  suffix = "(Province|Zone de Sant[e\u00e9]|Aire de Sant[e\u00e9]|Centre de Sant[e\u00e9])")
clean_dhis_names <- function(data, column, has_prefix = 2, 
                             suffix = "(Province|Zone de Sant[e\u00e9]|Aire de Sant[e\u00e9]|Centre de Sant[e\u00e9])"){
 clean_dhis_names_q(data, substitute(column), has_prefix, suffix)

}



#' Core of clean_dhis_names not exported.#'
#' @param data The dataset containing variables to be cleaned  
#' @param column The column containing values to be cleaned espcially organization levels of DRC EPI
#' @param has_prefix An integer specifying the number of characters of the prefix to be removed. Set to 0 if no prefix
#' @param suffix A character value that specifies the suffix to be removed
#'
#' @return
#' A dataframe with cleaned names

clean_dhis_names_q <- function(data, column, has_prefix = 2,
                               suffix = "(Province|Zone de Sant[e\u00e9]|Aire de Sant[e\u00e9]|Centre de Sant[e\u00e9])"){

  column1 <- eval(column, setNames(as.list(names(data)), names(data)), parent.frame())

  column <- column1

  stopifnot(!is.null(data), !is.null(column), is.character(column), is.character(suffix), is.numeric(has_prefix), length(column) == 1)

  if (!column %in% names(data)) stop("Column not found in data: ", column)

  has_prefix <- as.integer(has_prefix)

  suffix <- gsub("([.|()\\^{}+$*?]|\\[|\\]|\\\\)", "\\\\\\1", suffix)

  string <- paste0("(^[A-Za-z]", "{", has_prefix,"})|(", suffix,"$)")

  data[[column]] <- trimws(gsub(string, "", data[[column]], perl = TRUE), "both")

  if(suffix == "") warning("No suffix was trimmed")

  if(has_prefix == 0) warning("No prefix was trimmed")

  return(data)


}



#' A function that removes DRC's DHIS 2 prefixes and suffixes  from a vector
#'
#' @param x A character vector to be cleaned especially organization levels of DRC EPI. More convenient to use within other functions
#' @param has_prefix An integer specifying the number of characters of the prefix to be removed. Set to 0 if no prefix
#' @param suffix A character value that specifies the suffix to be removed
#'
#' @return
#' A character vector
#' @export
#'



clean_names_dhis <- function(x, has_prefix = 2, 
                             suffix = "(Province|Zone de Sant[e\u00e9]|Aire de Sant[e\u00e9]|Centre de Sant[e\u00e9])") {
  stopifnot(is.character(x), !is.null(x),  is.character(suffix), is.numeric(has_prefix))
  pattern <- paste0("(^[A-Za-z]{", has_prefix, "}\\s*)|(\\s*", suffix, "$)")

  cleaned <- trimws(gsub(pattern, "", x, perl = TRUE))

  return(cleaned)
}





