# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function to remove accented characters from all the character values of a data frame
#'
#' @param data Dataframe, usually the DHIS2 immunization dataframe
#' @param pattern A character value to match or a regular expression. Default "Ã©|Ã©"
#' @param replacement A character value to replace the pattern. Default "e"
#'
#' @return
#' A dataframe with values corrected
#' @export
#'
#' @examples
#' datafile <- system.file(c("vacc_data.RDS"), package = "pevrdc")
#'
#' vacc <- readRDS(datafile)
#' correct_accent(vacc, pattern =  "\u00C3\u00A9", replacement = "e")
correct_accent <- function(data, pattern = "\u00C3\u00A9", replacement = "e") {
  variables <- colnames(data)
  data_list <- Map(function(x)data[[x]] <- gsub(pattern, replacement, data[[x]], ), variables)
  data <- as.data.frame(data_list)

  colnames(data) <- tolower(gsub("\\.", "_", colnames(data)))

  return(data)
}


