# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A dataset containing DRC's 2024 target immunization populations at health districts levels
#'
#' @format A data frame with 519 observations and 6 variables:
#' \describe{
#'\item{orgunitlevel2}{character; Province}
#'\item{orgunitlevel3}{character; Zone de santé (health district)  }
#'\item{naissance_mois_admin}{numeric; monthly number of livebirths}
#'\item{survivants_mois_admin}{numeric; monthly number of surviving children}
#'\item{naissance_mois_ajust}{numeric; monthly number of livebirths ajusted}
#'\item{survivant_mois_ajust}{numeric; monthly number of surviving children ajusted}
#'\item{orgunitlevel6}{character; antenne}
#' }
#' @source Programme Élargie de Vaccination de RDC.
"pop2024"


#' A dataset containing DRC's 2024 target immunization populations at health districts levels
#'
#' @format A data frame with 519 observations and 6 variables:
#' \describe{
#'\item{orgunitlevel2}{character; Province}
#'\item{orgunitlevel3}{character; Zone de santé (health district)  }
#'\item{naissance_mois_admin}{numeric; monthly number of livebirths}
#'\item{survivants_mois_admin}{numeric; monthly number of surviving children}
#'\item{naissance_mois_ajust}{numeric; monthly number of livebirths ajusted}
#'\item{survivant_mois_ajust}{numeric; monthly number of surviving children ajusted}
#'\item{orgunitlevel6}{character; antenne}
#' }
#' @source Programme Élargie de Vaccination de RDC.
"pop2026"


#' A dataset containing DRC's health antennas and health districts
#'
#' @format A data frame with 519 observations and 3 variables:
#' \describe{
#'\item{province}{character; provinces}
#'\item{antenne}{character; health antennas}
#'\item{zonesante}{character; health zones}
#' }
#' @source Programme Élargie de Vaccination de RDC.
"antennes"

#' A dataset with simulated DHIS 2 imuundata containing DRC's health antennas and health districts
#' Please refer to DHIS 2 for a complete codebook of the data
#' @format A data frame with 1000 observations and 225 variables:
#' @source Programme Élargie de Vaccination de RDC.
"vacc_data"

#' A dataset containing DRC's 2025 target immunization populations at health districts levels
#'
#' @format A data frame with 519 observations and 6 variables:
#' \describe{
#'\item{orgunitlevel2}{character; Province}
#'\item{orgunitlevel3}{character; Zone de santé (health district)  }
#'\item{naissance_mois_admin}{numeric; monthly number of livebirths}
#'\item{survivants_mois_admin}{numeric; monthly number of surviving children}
#'\item{naissance_mois_ajust}{numeric; monthly number of livebirths ajusted}
#'\item{survivant_mois_ajust}{numeric; monthly number of surviving children ajusted}
#'\item{orgunitlevel6}{character; antenne}
#' }
#' @source Programme Élargie de Vaccination de RDC.
"pop2025"


#' A dataset with the DRC shapefile at health zone level, necessitate the sf package to load.
#' @format A data frame with 519 observations and 5 variables:
#' \describe{
#'\item{pays}{character}
#'\item{province}{character}
#'\item{antenne}{character}
#'\item{zonesante}{character}
#'\item{SHAPE}{multipolygon}
#' }
#' @source GRID-3.
"shape"
