# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' This is function is wrapper around is_outbreak to identify districts with an outbreak. 
#' @param df A dataset with a weekly number of cases or a logical indication of a case detected
#' @param district A variable containing districts names
#' @param wk A numeric variable specifying the successive week numbers 
#' @param status A logical or numeric variable with either indication of case recorded or the number of cases
#' @param nwk A numeric value that specifies the window frame for the assessment of consecutive logical values of x 
#' @param sorted A logical value to specify whether the dataset is ordered per week and district
#' @param pre_yr A logical value to specify whether dataset contains data from the previous year
#' @param year A numeric variable containing the year of the data
#' @return
#' A dataframe with an additional logical variable epi_status
#' @export
#'
#' @examples
#'
#' df <- data.frame(district = c(rep("A", 4), rep("B", 5)),
#'                  week = c(1:4, 1:5), 
#'                  status = c(TRUE, FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, FALSE))
#'
#' district_epi(df, district, week, status, 3, sorted = TRUE)
#'
district_epi <- function(df, district, wk, status, nwk = 4, sorted = FALSE, pre_yr = FALSE, year = NULL){

  district <- deparse1(substitute(district))

  wk <- deparse1(substitute(wk))

  status <- deparse1(substitute(status))

  if(!is.null(year))
    year <- deparse1(substitute(year))

  stopifnot(!is.null(df), !is.null(district), !is.null(wk), !is.null(status))


  if(!sorted)
    df <- df[order(df[[district]], df[[wk]]),]

  if(pre_yr){
    if(is.null(year))
      stop("year must be specified if pre_yr is set to TRUE")
    yr <- sort(unique(as.numeric(df[[year]])))
    if (length(yr) != 2)
      stop("pre_yr = TRUE requires exactly two distinct years in the dataset.")
    if((yr[2] - 1)!= yr[1])
      stop("Years are not consecutive")

    pre <- df[df[[year]] == yr[1]]

    current <- df[df[[year]] == yr[2]]

    pre <- pre[order(pre[[district]], pre[[wk]]),]

    current <- current[order(current[[district]], current[[wk]]),]

    df <- rbind(pre, current)}



  sp <- split(df, df[[district]])


  for (i in 1:length(sp)){

    sp[[i]][["epi_status"]] <- is_outbreak(sp[[i]][[status]], nwk = nwk)

  }

  epi_districts <- do.call(rbind, sp)

  row.names(epi_districts) <- NULL

  return(epi_districts)


}



#' This is function returns TRUE after n successive TRUE and FALSE otherwise. This is a convenient function to classify areas with outbreak following consecutive
#' positive cases of diseases recorded within n weeks.
#' @param x an ordered logical vector 
#' @param nwk a numeric value that specifies the window frame for the assessment of consecutive logical values of x 
#' @return
#' A logical vecor of similar length with x
#' @export
#'
#' @examples

#'
#' is_outbreak(c(TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE), 4)
#'
is_outbreak <- function(x, nwk = 4) {
  stopifnot(is.logical(x)|is.numeric(x))
  if(is.numeric(x)){
    x <- as.logical(x)
    warning("x was coerced to logical")
  }
  if (anyNA(x)){
    warning("NA values present; treated as FALSE")
    x[is.na(x)] <- FALSE}

  sapply(seq_along(x), function(i) {
    sum(x[max((i - nwk + 1),0):i]) >= 3
  })
}



