# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function to compute the cummulative monthly vaccine coverage  per organization levels using DHIS2 exported data
#'
#' @param data Dataframe, usually the DHIS2 immunization dataframe already aggregated
#' @param vaccine Column name of the vaccine of interest. Should be one of the following: BCG, DTC1, DTC3, VPO0, VAA, VAR1, VAR2, VPI1, VPI2, Pneumo13, Rota1, Rota2, Rota3, VAP1, VAP2, VAP3, VAP4, DTC2, Pneumo13_2, VPI 2, VPO1, VPO2, VPO3 & TD2 
#' @param level The column name or vector of column names of the aggregation level of interest. Should be any of Country, Province, District or Antenne 
#' @param month An integer between 1 to 12 that specifies the cummulative period of months to aggregate date
#' @param pops An aggregated dataset of target populations.
#' @importFrom stats aggregate reformulate setNames
#' @return
#' A dataframe with vaccines coverage 
#' @export
#'
#' @examples

#' datafile <- system.file(c("vacc_data.RDS", "pop2025.RDS"), package = "pevrdc")
#'
#' vacc <- readRDS(datafile[1])
#' pops <- readRDS(datafile[2])
#' vacc_tots <- vaccine_sums(vacc, DTC1, District, 2)
#' vaccine_coverage(vacc_tots, DTC1, District, month = 2, pops = pops)
#'
vaccine_coverage <- function(data, vaccine, level, month = 1, pops) {
  vac <- c(
    "BCG", "DTC1", "DTC3", "VPO0", "VAA", "VAR1", "VAR2", "VPI1",
    "VPI2", "Pneumo13", "Rota1", "Rota2", "Rota3", "VAP1", "VAP2",
    "VAP3", "VAP4", "DTC2", "Pneumo13_2", "VPI 2", "VPO1", "VPO2",
    "VPO3", "TD2"
  )
  unit <- c(
    "Country" = "orgunitlevel1", "Province" = "orgunitlevel2", "District" = "orgunitlevel3", "Aire" = "orgunitlevel4",
    "Fosa" = "orgunitlevel5", "Antenne" = "orgunitlevel6"
  )

  level1 <- eval(substitute(level), stats::setNames(as.list(unit), names(unit)), parent.frame())

  vaccine1 <-{if(is.character(deparse1(substitute(vaccine)))) as.character(substitute(vaccine)) else deparse1(substitute(vaccine))}

  vaccine <- vaccine1

  stopifnot(is.numeric(month), !is.null(data), vaccine %in% vac, vaccine %in% colnames(data), all(level1 %in% unit))

  level <- level1



  data <- stats::aggregate(stats::reformulate(level, response = vaccine), FUN = sum, data = data)


  if (vaccine %in% c("BCG", "VPO0")) {
    num_vars <- c("naissance_mois_admin", "naissance_mois_ajust")
  } else {
    num_vars <- c("survivants_mois_admin", "survivant_mois_ajust")
  }

  pop1 <- agg_pop_2(num_vars[1],level, month = month, pops = pops)
  pop2 <- agg_pop_2(num_vars[2],level, month = month, pops = pops)


  populations <- merge(pop1, pop2, by = level)



  merged_data <- merge(data, populations, by = level)



  merged_data[[paste0(vaccine, "_admin")]] <- round(100 * merged_data[[vaccine]] / merged_data[[num_vars[1]]], 2)
  merged_data[[paste0(vaccine, "_ajust")]] <- round(100 * merged_data[[vaccine]] / merged_data[[num_vars[2]]], 2)

  if(vaccine == "DTC1"){
    merged_data[["zero_dose_admin"]] <- round(merged_data[[num_vars[1]]] - merged_data[[vaccine]])
    merged_data[["zero_dose_ajust"]] <- round(merged_data[[num_vars[2]]] - merged_data[[vaccine]])

  }

  return(merged_data)
}


