# WARNING - Generated by {fusen} from dev/flat_first.Rmd: do not edit by hand # nolint: line_length_linter.

#' A function to compute the cummulative monthly tally of vaccinated per organization levels using DHIS2 exported data
#'
#' @param data Dataframe, usually the DHIS2 immunization dataframe
#' @param vaccine Column name of the vaccine of interest. Should be one of the following: BCG, DTC1, DTC3, VPO0, VAA, VAR1, VAR2, VPI1, VPI2, Pneumo13, Rota1, Rota2, Rota3, VAP1, VAP2, VAP3, VAP4, DTC2, Pneumo13_2, VPI 2, VPO1, VPO2, VPO3 & TD2 
#' @param level The column name or vector of column names of the aggregation level of interest. Should be any of Country, Province, District, or Antenne 
#' @param month An integer between 1 to 12 that specifies the cummulative period of months to aggregate date
#' @param accent A logical to specify whether the dataset values contains accented characters. Set to TRUE as default 
#' @importFrom stats aggregate reformulate setNames
#' @return
#' A dataframe with aggregated sums of vaccinated between 
#' @export
#'
#' @examples
#' datafile <- system.file(c("vacc_data.RDS"), package = "pevrdc")
#'
#' vacc <- readRDS(datafile)
#' vaccine_sums(vacc, DTC1, District, 2)
vaccine_sums <- function(data, vaccine, level, month = 1, accent = TRUE) {
  vacc_list <- c(
    "BCG" = "bcg_0_et_11_mois",
    "DTC1" = "dtc_hepb_hib1_0_et_11",
    "DTC3" = "dtc_hepb_hib3_0_et_11",
    "VPO0" = "vpo_0_0_et_11",
    "VAA" = "vaa_0_et_11",
    "VAR1" = "var_1_rr_1_0_et_11",
    "VAR2" = "var_2_rr_2_0_et_11_mois|var_2_rr_2_12_et_23_mois",
    "VPI1" = "vpi_1_0_et_11",
    "VPI2" = "vpi_2_0_et_11",
    "Pneumo13" = "pcv_13__1__0_et_11",
    "Rota1" = "rota_1_0_et_11",
    "Rota2" = "rota_2_0_et_11",
    "Rota3" = "rota_3_0_et_11",
    "VAP1" = "vap_1_0_et_11",
    "VAP2" = "vap_2_0_et_11",
    "VAP3" = "vap_3_0_et_11",
    "VAP4" = "vap_4_0_et_11|vap_4_12_et_23",
    "DTC2" = "dtc_hepb_hib2_0_et_11",
    "Pneumo13_2" = "pcv_13__2__0_et_11",
    "VPI 2" = "vpi_2_0_et_11_mois",
    "VPO1" = "vpo_1_0_et_11",
    "VPO2" = "vpo_2_0_et_11",
    "VPO3" = "vpo_3_0_et_11",
    "TD2" = "td_[2-5]"
  )

  unit <- c(
    "Country" = "orgunitlevel1", "Province" = "orgunitlevel2", "District" = "orgunitlevel3", "Aire" = "orgunitlevel4",
    "Fosa" = "orgunitlevel5", "Antenne" = "orgunitlevel6"
  )

  vaccine1 <- {if(is.character(deparse1(substitute(vaccine)))) as.character(substitute(vaccine)) else deparse1(substitute(vaccine))}

  level1 <- eval(substitute(level), stats::setNames(as.list(unit), names(unit)), parent.frame())


  stopifnot(length(vaccine1) == 1, !is.null(data), vaccine1 %in% names(vacc_list), all(level1 %in% unit), !is.null(level1), !is.null(vaccine1))
  
  if(month < 1 || month > 12)
    stop("month should be between 1 and 12")
  
  if(accent)
    data <- correct_accent(data)

  level <- level1
  vacc_name <- vaccine1
  vaccine <- vacc_list[vaccine1]
  # Adding antenna
  if (any(grepl("Antenne", names(level)))) {
    # Adding antenna
    data <- add_antennes(data, dhis = TRUE)
    message("Antennes were added to the data")
  }


  data <- do.call(cbind, list(data["periodname"], data[level], Map(as.numeric, data[grepl(vaccine, colnames(data))])))


  # removing all NAs
  data[is.na(data)] <- 0
  # Calculating the period

  syst_time <- Sys.getlocale("LC_TIME")

  Sys.setlocale(category = "LC_TIME", locale = "English_United States.utf8")


  period <- c(
    "Janvier" = 1, "Fevrier" = 2, "Mars" = 3, "Avril" = 4, "Mai" = 5, "Juin" = 6, "Juillet" = 7,
    "Aout" = 8, "Septembre" = 9, "Octobre" = 10, "Novembre" = 11, "Decembre" = 12
  )
  period_eng <- c(
    "January" = 1, "February" = 2, "March" = 3, "April" = 4, "May" = 5, "June" = 6, "July" = 7,
    "August" = 8, "September" = 9, "October" = 10, "November" = 11, "December" = 12
  )
  if (all(nchar(as.character(data[["periodname"]])) == 10)) {
    data[, "periodname"] <- as.Date(data[["periodname"]])
    data$period <- period_eng[format(data$periodname, "%B")]
  } else {
    data$period <- unname(period[trimws(gsub("[0-9]", "", data$periodname), "both")])
  }
  
  data <- subset(data, period <= month)

  on.exit(Sys.setlocale(category = "LC_TIME", locale = syst_time))

  data$vaccsum <- Reduce(`+`, data[, grepl(vaccine, colnames(data))])

  vacc_agg <- stats::aggregate(stats::reformulate(level, response = "vaccsum"), data = data, FUN = sum)


  names(vacc_agg)[names(vacc_agg) == "vaccsum"] <- vacc_name

  return(vacc_agg)
}




